url: "https://faithfulpack.net"

compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - node_modules
  - /package*.json
  - /index.js
  - /.github
  - /README.md

sass:
  sass_dir: css
  sourcemap: never
  style: compressed
